export const directors = [
	'J.J. Abrams',
	'Wes Anderson',
	'Tim Burton',
	'James Cameron',
	'Chris Columbus',
	'Alfonso Cuaron',
	'Peter Jackson',
	'George Lucas',
	'Sam Mendes',
	'Christopher Nolan',
	'Guy Ritchie',
	'Martin Scorsese',
	'Ridley Scott',
	'Steven Spielberg',
	'Quentin Tarantino',
	'Denis Villeneuve',
	'Taika Waititi',
	'Edgar Wright',
	'David Yates',
];
